# Generated by Django 4.0.7 on 2022-08-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_station', models.CharField(max_length=11)),
                ('date', models.DateField()),
                ('max_temp_of_day', models.IntegerField(null=True)),
                ('min_temp_of_day', models.IntegerField(null=True)),
                ('precipitation_of_day', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'weather_data',
            },
        ),
        migrations.CreateModel(
            name='YieldData',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('total_harvested_grain', models.IntegerField()),
            ],
            options={
                'db_table': 'yield_data',
            },
        ),
        migrations.AddConstraint(
            model_name='weatherdata',
            constraint=models.UniqueConstraint(fields=('weather_station', 'date'), name='unique_date_per_station'),
        ),
    ]
