# Generated by Django 4.0.7 on 2022-08-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weatherdata',
            name='unique_date_per_station',
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='weather_station',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together={('weather_station', 'date')},
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='id',
        ),
    ]
