# Generated by Django 4.0.7 on 2022-08-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weatherdata',
            name='unique_date_per_station',
        ),
    ]
