# Generated by Django 4.0.7 on 2022-08-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_weatherdata_unique_date_per_station_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yielddata',
            name='id',
        ),
        migrations.AlterField(
            model_name='yielddata',
            name='year',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
