# Generated by Django 4.0.7 on 2022-08-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_weatherdata_unique_date_per_station'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='weatherdata',
            constraint=models.UniqueConstraint(fields=('weather_station', 'date'), name='unique_date_per_station'),
        ),
    ]
