# Generated by Django 4.0.7 on 2022-08-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_weatherdata_unique_date_per_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_station', models.CharField(max_length=11)),
                ('year', models.IntegerField()),
                ('avg_max_temp_of_year', models.IntegerField(null=True)),
                ('avg_min_temp_of_year', models.IntegerField(null=True)),
                ('total_precipitation_of_year', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'weather_analysis',
            },
        ),
        migrations.AddConstraint(
            model_name='weatheranalysis',
            constraint=models.UniqueConstraint(fields=('weather_station', 'year'), name='unique_year_per_station'),
        ),
    ]
