# Generated by Django 4.0.7 on 2022-08-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_weatheranalysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatheranalysis',
            name='avg_max_temp_of_year',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weatheranalysis',
            name='avg_min_temp_of_year',
            field=models.FloatField(null=True),
        ),
    ]
