# Generated by Django 4.0.7 on 2022-08-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_weatheranalysis_avg_max_temp_of_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yielddata',
            name='id',
            field=models.BigAutoField(auto_created=True, default='123', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yielddata',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
